import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import EmployeeForm from "@/components/_employeeFrom";
import DynamicFrom from "@/components/_dynamicForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const formFields = [
    { name: 'firstName', label: 'First Name', type: 'text' },
    { name: 'lastName', label: 'Last Name', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'message', label: 'Message', type: 'textarea' },
    { name: 'gender', label: 'Gender', type: 'radio', options: ['Male', 'Female', 'Other'] },
    { name: 'subscribe', label: 'Subscribe', type: 'checkbox' },
    { name: 'Image', label: 'Image', type: 'file' },
    // { name: 'profileImage', label: 'Profile Image', type: 'file', accept: '.jpg,.jpeg,.png' },
    // { name: 'document', label: 'Document', type: 'file', accept: '.pdf,.doc,.docx' },
    {
      name: 'country', label: 'Country', type: 'select', options: [{ value: 1, name: 'USA' },
      { value: 2, name: 'CANADA' }, { value: 2, name: 'CANADA' }]
    },
  ];


  const arr = [
    { id: 1, countryName: "Bangladesh" },
    { id: 2, countryName: "Indai" },
    { id: 3, countryName: "Pakist" }
  ]

  arr.map((data, i) => console.log(data["id"]))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        {/* <EmployeeForm/> */}
        <DynamicFrom fields={formFields} />
      </main>
    </>
  );


}
